### ISSUE TITLE
Cannot Choose Rendering Platform and Several Bugs

### ISSUE THREAD

**Issue by luyuju151** [mfeemster/fractorium#29]
Thanks for your great project! I am using Fractorium rendering my flames. Fractorium can render one flame in 5 seconds in openCL mode with NVIDIA GTX 970M, while it takes 5 minutes using Apophysis7X on CPU. That's amazing!

But recently, I was testing `fractorium 0.9.9.1 Beta 09/19/2015` and found that the command line argument `--platform` for `EmberRender.exe` was cancelled. I have two platforms:

```
EmberRender.exe --openclinfo

OpenCL Info:
Platform 0: Intel(R) Corporation Intel(R) OpenCL OpenCL 1.2
Device 0: Intel(R) Corporation Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.2
...

Device 1: Intel(R) Corporation Intel(R) HD Graphics 4600
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.2
...

Platform 1: NVIDIA Corporation NVIDIA CUDA OpenCL 1.1 CUDA 6.5.19
Device 0: NVIDIA Corporation GeForce GTX 970M
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.1
...
```

Now I can't choose `Platform 1,Device 0`  NVIDIA GPU OpenCL for rending in `0.9.9.1 Beta 09/19/2015` by `--platform=1 --device=0`. I tried `--device=0` or `1` or `2` or `3` or `0,1,2` or `1,0` , just didn't work .(It used Intel platform or crashed)

_ _ _
![screenshot_1](https://cloud.githubusercontent.com/assets/10216029/10581842/477e51a6-76b7-11e5-96b7-b9ed7efea885.png)

I also noticed that in `Fractorium.exe` if I selected `Tools -> Options` in the column `Use` `NVIDIA Corporation GeForce GTX970M` and clicked `OK`, it crashed: 

`"Renderer Creation Error", "Could not create requested renderer, fallback CPU renderer created. See info tab for details."`

and then

`"Renderer Creation Error", "Error creating renderer, most likely a GPU problem. Using CPU instead."`

_ _ _

Moreover, if I opened Fractorium.exe and just closed, it also crashed:

```
Microsoft Visual C++ Runtime Library
Runtime Error!
Program: F:\FractalArt\Fractorium\Fractorium.exe
R6025
- pure virtual function call
```
![screenshot_2](https://cloud.githubusercontent.com/assets/10216029/10581918/b2a1e560-76b7-11e5-97e3-8dd4cbffb053.png)
and

```
Problem Event Name:	APPCRASH
Application Name:	Fractorium.exe
Application Version:	0.9.9.1
Application Timestamp:	5600a091
Fault Module Name:	IntelOpenCL64.dll
Fault Module Version:	10.18.10.3621
Fault Module Timestamp:	5376e303
Exception Code:	40000015
Exception Offset:	000000000002c332
OS Version:	6.1.7601.2.1.0.256.1
Locale ID:	2052
Additional Information 1:	bbc9
Additional Information 2:	bbc93cdffea57db003849710caea69d0
Additional Information 3:	527a
Additional Information 4:	527aad2071300d6b97115c107bfd69ee
```

After ticking `Use OpenCL` in `Options`, it crashed
```
Problem Event Name:	BEX64
Application Name:	Fractorium.exe
Application Version:	0.9.9.1
Application Timestamp:	5600a091
Fault Module Name:	StackHash_1dc2
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	00000000
Exception Offset:	0000000000000000
Exception Code:	c0000005
Exception Data:	0000000000000008
OS Version:	6.1.7601.2.1.0.256.1
Locale ID:	2052
Additional Information 1:	1dc2
Additional Information 2:	1dc22fb1de37d348f27e54dbb5278e7d
Additional Information 3:	eae3
Additional Information 4:	eae36a4b5ffb27c9d33117f4125a75c2
```

_ _ _

It was all fine in `0.4.1.8 Beta`. Hope these bugs will be fixed and Fractorium will be more and more popular. Thanks!

(OS:Windows 7, 64bit; Locale:Simplified Chinese)

**Comment by mfeemster** [comment]
Hi luyu, my apologies for the problems. The good news is, there's nothing wrong =) A few points:

-All of the recent changes are summarized here:
http://mfeemster.deviantart.com/journal/Fractorium-Beta-0-9-9-0-Released-561330048

-I know it's not good to have documentation spread out across multiple sites, but I spend so much time on code, I have zero time left for actually explaining it =(

I am currently working very hard on implementing a few more features, at which point I will hang up development and switch my efforts to making a nice website with documentation and video tutorials. I can spend time doing code, or documentation, but not both.

-For your system, you only want to use the Nvidia card, as I do not support Intel yet simply because I don't have an Intel HD processor to test on.

--For your system, when running on the command line, just specify --device=2
--When running in Fractorium, use only the Nvidia card, and specify it as the primary (explanation of the concept of primary in the link above).

-The pure virtual function call error has something to do with using Intel OpenCL. Just use your Nvidia card and I think it will go away. I'll eventually fix it whenever I get an Intel HD chip to test on sometime in the distant future.

Let me know how it goes.

**Comment by luyuju151** [comment]
Hi, mfeemster, thanks for your quick reply. I read your link above and tried `--device=2` for `EmberRender.exe` and changed the OpenCL options for `Fractorium.exe`, but it still crashed.

![screenshot_1](https://cloud.githubusercontent.com/assets/10216029/10584762/6d9db232-76c6-11e5-8fe3-f386edf84080.png)

Then I read your [[Release Journal]](http://mfeemster.deviantart.com/journal/Fractorium-Beta-0-9-9-0-Released-561330048), noticing :
```
-Single installer.
    Nvidia has been dragged kicking and screaming into 3 years ago and has finally supported OpenCL 1.2.
    This means I no longer have to provide separate AMD and Nvidia installers, there is now just one.
    Be sure to install the latest drivers for your card.
```
I realized my NVIDIA OpenCL is `OpenCL 1.1`, which is outdated. It seems that NVIDIA 350.05 and new driver supports OpenCL 1.2 [[link]](http://www.anandtech.com/show/9139/nvidia-posts-35005-hotfix-driver-fixes-games-adds-opencl-12-support). After updating NVIDIA driver to 358.50, the commandLine arguments `--opencl --device=2` worked and the OpenCL options for `Fractorium.exe` were changed successfully. I am able to rendering flames in the blink of an eye again. ：）


But the pure virtual function call error still exists, every time I close `Fractorium.exe` or finish rendering with `EmberRender.exe`. I guess the error may be rellated with "Intel Graphics and NVIDIA with Optimus" on laptops. User cannot force a program to be run under NVIDIA card only. It dosen't matter much, since I have gotten my png rendered.

![screenshot_2](https://cloud.githubusercontent.com/assets/10216029/10584768/76ca3b50-76c6-11e5-9327-ba943077ed40.png)

The problem is settled and I appreciate your help very much. I wrote my experiences above in case it may help someone with the same problem.

**Comment by mfeemster** [comment]
Glad you got it working!

As for the pure virtual function call thing, that is starting to bug me since others have also reported it. I will install the Intel OpenCL drivers and attempt to debug this problem over the coming days and weeks. Hopefully I can find a fix.

**Comment by mfeemster** [comment]
I have been able to identify the "pure virtual function call" error on shutdown after I got my hands on a machine with only an Nvidia card on it.

This is probably TMI, but here was the source of the problem:

I use a singleton pattern to query OpenCL about all devices on the system. I do this because there is no sense in doing it more than once during the life of the program. While singletons are useful and efficient, they can lead to weird problems because they get destroyed after main() exits. Apparently AMD's OpenCL implementation is fine with this, however Nvidia's crashes. Likely because in their destructors, they are trying to reference some other object that has already been destroyed.

I will come up with a way to use the singleton pattern while also ensuring the object is destroyed before main() exits. Most likely some usage of std::shared_ptr.

This will be fixed in the next release, so keep an eye out.

**Comment by luyuju151** [comment]
Thanks! I'm looking forward to the fix! 
I struggled to build fractorium using the `.pro`s under `fractorium\Builds\QtCreator` today with Qt Creater, Qt 5.5.1 64bit and MSVC 2013 win7. As an amateur programmer the building experience was painful, but I am eager to update the edited qt `.pro`s for win32 when I am free agian next week.

**Comment by mfeemster** [comment]
To be honest, this isn't intended to be built by many people, it's a lot of work. In fact I just identified a few problems in the MSVC project files that I'll be updating in a few weeks. However if you're a glutton for pain, have at it:

https://github.com/mfeemster/fractorium/wiki/Building

If you prefer not to be in pain, just download the installer and run it.

**Comment by luyuju151** [comment]
Without `wiki/Building`, I couldn't even figure out where I should start. I could have followed the wiki but I found Visual Studio 2013 was toooo big and used the extracted VC++ complier only. I think I learned a lot from building and am now very happy with the painful experience. Maybe you are right, I a glutton for pain (and for fun). :)

**Comment by mfeemster** [comment]
As a general rule: always read the documentation first.
