### ISSUE TITLE
No palettes found, exiting.

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#33]
I ran into this while installing the Fractorium binary to `/usr/bin`. Right on startup, it is looking for palettes such as `flam3-palettes.xml`, but only looking in the folder where the binary is.

In `Fractorium/FractoriumEmberController.cpp` I found:

```
if (!InitPaletteList(QCoreApplication::applicationDirPath().toLocal8Bit().data()))
    throw "No palettes found, exiting.";
```

During the linux installation, I would like to copy `flam3-palettes.xml` to `/usr/share/fractorium` (lowercase if possible), and it would be best if Fractorium could look for it there as one of the locations.

[doc.qt.io](http://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum) says this would be `QStandardPaths::DataLocation`. I hard-coded the path just to let it run, but one of these standard data or config folders would be the place to go.

**Comment by gh2k** [comment]
Yeah, I concur that locating flam3-palettes.xml has been awkward on Linux. Also, that `throw` statement bombs horribly as there's no exception handler anywhere that knows how to handle a char*, so the application segfaults with no output. It's hard to work around if you don't know about it.

**Comment by mfeemster** [comment]
I've tested this without a palette file in Fractorium and get a fatal error popup saying "No palettes found, exiting.". I think this is sufficient handling, and is done through this catch block in Main.cpp:

catch (const char* e)
{
	QMessageBox::critical(0, "Fatal Error", e);
}

I have spotted some flaws in how it's processed in the command line programs and am fixing it now.

As for the installation folder, I would like everything to be self contained in one folder. For example, on the Mint 17 install I am running right now, I see firefox installed to: /opt/firefox42, and inside that folder appears to everything it needs to run. There is a shortcut to the executable in /usr/bin.

Going off this:

https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

I think it's fine to place the executable outputs, stylesheet and the palette file in /opt/fractorium, and then make a shortcut to it from /usr/bin. What do you think of that?

**Comment by gambhiro** [comment]
> As for the installation folder, I would like everything to be self contained in one folder. For example, on the Mint 17 install I am running right now, I see firefox installed to: /opt/firefox42, and inside that folder appears to everything it needs to run. There is a shortcut to the executable in /usr/bin.

`/opt` is usually a shorthand solution. An application that uses it still has to symlink into the standard `bin`, `etc` and `lib` locations for it to work.

You picked an example that is an exception rather than the common practice. The firefox package only seems to use `/opt` on Linux Mint. See the list of its installed files for Ubuntu at the bottom.

Someone with greater experience could probably give a deeper insight, but symlinking to `/opt` only seems to be practised when the application has some complex folder structure it wants to maintain (the [XAMPP](https://www.apachefriends.org) bundle does this for example) or it is a port from Windows and this was a quick way to get things moving.

Atm I am on Ubuntu 15.04 and only Google Earth and a PDF editor are using `/opt`:

```
$ ls /opt                                                                    
google  master-pdf-editor-3
```

In `/opt/google/earth/free/` there are 105 files, while the PDF editor (a Qt app) only has a handful that don't need `/opt`, perhaps it just indicates he wants to sort this out later.

```
$ ls /opt/master-pdf-editor-3                                                
lang  license.txt  masterpdfeditor3  masterpdfeditor3.png
```

Selecting firefox in Synaptic, right click, Properties > Installed files gives me:

```
/.
/etc
/etc/apparmor.d
/etc/apparmor.d/disable
/etc/apparmor.d/usr.bin.firefox
/etc/apport
/etc/apport/blacklist.d
/etc/apport/blacklist.d/firefox
/etc/apport/native-origins.d
/etc/apport/native-origins.d/firefox
/etc/firefox
/etc/firefox/syspref.js
/usr
/usr/bin
/usr/bin/firefox
/usr/lib
/usr/lib/firefox
/usr/lib/firefox-addons
/usr/lib/firefox-addons/distribution
/usr/lib/firefox-addons/distribution/extensions
/usr/lib/firefox-addons/extensions
/usr/lib/firefox-addons/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
/usr/lib/firefox-addons/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}/chrome.manifest
/usr/lib/firefox-addons/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}/icon.png
/usr/lib/firefox-addons/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}/install.rdf
/usr/lib/firefox-addons/plugins
/usr/lib/firefox-addons/searchplugins
/usr/lib/firefox/Throbber-small.gif
/usr/lib/firefox/application.ini
/usr/lib/firefox/browser
/usr/lib/firefox/browser/blocklist.xml
/usr/lib/firefox/browser/chrome
/usr/lib/firefox/browser/chrome.manifest
/usr/lib/firefox/browser/chrome/icons
/usr/lib/firefox/browser/chrome/icons/default
/usr/lib/firefox/browser/chrome/icons/default/default16.png
/usr/lib/firefox/browser/chrome/icons/default/default32.png
/usr/lib/firefox/browser/chrome/icons/default/default48.png
/usr/lib/firefox/browser/components
/usr/lib/firefox/browser/components/components.manifest
/usr/lib/firefox/browser/components/libbrowsercomps.so
/usr/lib/firefox/browser/defaults
/usr/lib/firefox/browser/defaults/preferences
/usr/lib/firefox/browser/defaults/preferences/syspref.js
/usr/lib/firefox/browser/defaults/preferences/vendor-firefox.js
/usr/lib/firefox/browser/extensions
/usr/lib/firefox/browser/icons
/usr/lib/firefox/browser/icons/mozicon128.png
/usr/lib/firefox/browser/omni.ja
/usr/lib/firefox/browser/plugins
/usr/lib/firefox/browser/searchplugins
/usr/lib/firefox/chrome.manifest
/usr/lib/firefox/components
/usr/lib/firefox/components/components.manifest
/usr/lib/firefox/components/libdbusservice.so
/usr/lib/firefox/components/libmozgnome.so
/usr/lib/firefox/crashreporter
/usr/lib/firefox/crashreporter.ini
/usr/lib/firefox/defaults
/usr/lib/firefox/defaults/pref
/usr/lib/firefox/defaults/pref/channel-prefs.js
/usr/lib/firefox/defaults/pref/vendor-gre.js
/usr/lib/firefox/dependentlibs.list
/usr/lib/firefox/dictionaries
/usr/lib/firefox/distribution
/usr/lib/firefox/distribution/distribution.ini
/usr/lib/firefox/distribution/extensions
/usr/lib/firefox/distribution/searchplugins
/usr/lib/firefox/distribution/searchplugins/common
/usr/lib/firefox/distribution/searchplugins/locale
/usr/lib/firefox/distribution/searchplugins/locale/en-US
/usr/lib/firefox/distribution/searchplugins/locale/en-US/amazondotcom.xml
/usr/lib/firefox/distribution/searchplugins/locale/en-US/ddg.xml
/usr/lib/firefox/distribution/searchplugins/locale/en-US/google.xml
/usr/lib/firefox/firefox
/usr/lib/firefox/firefox.sh
/usr/lib/firefox/gmp-clearkey
/usr/lib/firefox/gmp-clearkey/0.1
/usr/lib/firefox/gmp-clearkey/0.1/clearkey.info
/usr/lib/firefox/gmp-clearkey/0.1/libclearkey.so
/usr/lib/firefox/hyphenation
/usr/lib/firefox/libfreebl3.chk
/usr/lib/firefox/libfreebl3.so
/usr/lib/firefox/liblgpllibs.so
/usr/lib/firefox/libmozsqlite3.so
/usr/lib/firefox/libnspr4.so
/usr/lib/firefox/libnss3.so
/usr/lib/firefox/libnssckbi.so
/usr/lib/firefox/libnssdbm3.chk
/usr/lib/firefox/libnssdbm3.so
/usr/lib/firefox/libnssutil3.so
/usr/lib/firefox/libplc4.so
/usr/lib/firefox/libplds4.so
/usr/lib/firefox/libsmime3.so
/usr/lib/firefox/libsoftokn3.chk
/usr/lib/firefox/libsoftokn3.so
/usr/lib/firefox/libssl3.so
/usr/lib/firefox/libxul.so
/usr/lib/firefox/omni.ja
/usr/lib/firefox/platform.ini
/usr/lib/firefox/plugin-container
/usr/lib/firefox/webapprt
/usr/lib/firefox/webapprt-stub
/usr/lib/firefox/webapprt/defaults
/usr/lib/firefox/webapprt/defaults/preferences
/usr/lib/firefox/webapprt/defaults/preferences/vendor-webapprt.js
/usr/lib/firefox/webapprt/extensions
/usr/lib/firefox/webapprt/omni.ja
/usr/lib/firefox/webapprt/webapprt.ini
/usr/share
/usr/share/applications
/usr/share/applications/firefox.desktop
/usr/share/apport
/usr/share/apport/package-hooks
/usr/share/apport/package-hooks/source_firefox.py
/usr/share/doc
/usr/share/doc/firefox
/usr/share/doc/firefox/MPL.gz
/usr/share/doc/firefox/README.Debian
/usr/share/doc/firefox/changelog.Debian.gz
/usr/share/doc/firefox/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/firefox
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/firefox.1.gz
/usr/share/pixmaps
/usr/share/pixmaps/firefox.png
```

**Comment by mfeemster** [comment]
With your package commit, I believe we have this resolved. Are you alright with closing it?

**Comment by MAD-OVERLORD** [comment]
@mfeemster 
Believing is something only child fucking creeps practice in their giant monuments of decadence :S 
In other words, i am still affected by this on a Linux Mint17 X64.
Fractorium sadly didn't compile because of 
https://github.com/mfeemster/fractorium/issues/51
but the emberanimate, embergenome, emberrender, libEmber.so, libEmberCL.so were build, so i injected all the stuff that was missing from the fractorium_0.9.9.3b-0ubuntu1_amd64.deb according to the paths there and added my compiled bins.
Of course the borrowed fractorium bin didn't work, but the compiled emberrender which i had thought may work this way, exited with

Error parsing palette file flam3-palettes.xml. Reason: 
Add : Couldn't read palette file flam3-palettes.xml
Returning without executing.

on
emberrender --in="/tmp/test.flam3" --out="/tmp/output.png" --format=png --verbose --progress
but as far as i can see, there is nothing wrong with the place or permissions, since i extracted it right out of the fractorium_0.9.9.3b-0ubuntu1_amd64.deb from your github page.
/usr/share
drwxr-xr-x    2 root  root   4096 Jan 20 19:05 fractorium
/usr/share/fractorium
-rw-r--r--   1 root root   11326 Dez 15 16:25 dark.qss
-rw-r--r--   1 root root 1496739 Dez 15 16:25 flam3-palettes.xml
-rw-r--r--   1 root root   65364 Jan 20 09:42 Fractorium.png

So how can i fix this?

**Comment by gambhiro** [comment]
Do have another go at compiling from Github, see [BuildGuideLinux.md](https://github.com/mfeemster/fractorium/blob/master/Data/BuildGuideLinux.md). After the dependencies, `qmake && make` in the project folder should build a binary in `Bin/release/`.

**Comment by nonno-cicala** [comment]
@MAD-OVERLORD You could also specify the path to flam3-palettes.xml in the command line with --flam3_palettes=/usr/share/fractorium/flam3-palettes.xml

@mfeemster @gh2k @gambhiro @luyuju151 Thank you very much for your work on this awesome project!
I successfully built and ran it on my gentoo; if anybody knows someone who has an ebuild it would be great, otherwise I could try to write one in the future.

**Comment by mfeemster** [comment]
@nonno-cicala Hi there, glad you like it and have things working well. I'm curious, how did the build process go on gentoo? I am hoping it went smoothly. I always hate when trying to build something and there is "just... one... more... thing...". In my view, things should build right out of the box with no hassle, so I would really hate to be contributing to stuff that is tough to build. So please let us know here how it went.

As for making an installer, @gambhiro handles that since I only focus on the Windows side and @gh2k handles the soon-to-be Mac installer. It's up to either of them if they want to work on gentoo. If not, I'd welcome you to take a stab at it.

**Comment by mfeemster** [comment]
@MAD-OVERLORD Glad you at least got the command line programs running. Regarding the palette file, it's expected to be in the same folder as the program. But like @nonno-cicala said, you can specify the path to it if you want.

@gambhiro When I build on Windows, I use a post build step to always ensure the palette file is copied from /Data to the output folder. Do we have such a thing on our Linux build? If not, can we please add it?

Thanks all.

**Comment by nonno-cicala** [comment]
@mfeemster After I installed all the deps with packages already available in the main tree (IIRC) I had to explicitly set what Qt version to use exporting the variable QT_SELECT=qt5, otherwise it tried to use Qt4.
Then I did 2 other things, but I think they weren't necessary:
I edited Builds/create-symlinks.sh because I don't have the paths /usr/include/*/GL and /usr/include/*/CL , so I changed them to /usr/include/GL and /usr/include/CL ;
and I changed line 100 in Builds/QtCreator/defaults.pri from QMAKE_CXXFLAGS += -march=k8 to QMAKE_CXXFLAGS += -march=native , because I don't know how I could enter that "native" instruction I found 2 lines before (btw how does that work? Do I have to add anything when running qmake?).

So the process was straightforward, except for the need to set what Qt version to use.

**Comment by MAD-OVERLORD** [comment]
@nonno-cicala  
Thanks for the hint, i just never before thought about getting familiar with that much parameters of a software, which previously crapped out at compiling and didn't show any basic life signs besides bad ones like
emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by emberrender)
emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /usr/lib/libEmberCL.so)
emberrender: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /usr/lib/libEmberCL.so)
but on linux "specialists" never really stop learning :D

Since no one wrote back, i guess no one has understood the point of your brilliant joke about basically saying "It was easy, i just changed everything and then it worked right out of the box" :D:D:D

**Comment by mfeemster** [comment]
"It was easy, i just changed everything and then it worked right out of the box"

There's an entire operating system built around that philosophy.. it's called Linux!

***ducks!***

In all seriousness, @gambhiro can you take a look at the points @nonno-cicala mentioned. Can we check for the existence of various folders when trying to make the symlinks?

And what is the point of this part:

!win32 {
  native {
    QMAKE_CXXFLAGS += -march=native
  } else {
    QMAKE_CXXFLAGS += -march=k8
  }
}

I can't remember who added that, maybe @gh2k ?

**Comment by gambhiro** [comment]
Thanks @nonno-cicala, #52 should help others.

```
!win32 {
  native {
    QMAKE_CXXFLAGS += -march=native
  } else {
    QMAKE_CXXFLAGS += -march=k8
  }
}
```

For Linux and Mac, this selects compiler optimizations for AMD64 (k8) by default. Is that a harmful assumption? It may or may not impact performance, I don't know.

To select the native option, one has to specify it with `qmake "CONFIG += native"`.

**Comment by gambhiro** [comment]
@mfeemster Yes, qmake copies `flam3-palettes.xml` to `Bin/release` on manual build, and `make install` or the the .deb installs it to `/usr/share/fractorium`.

**Comment by mfeemster** [comment]
@gambhiro Thanks. It sounds like we have no bugs concerning this then.

Can others try to build again from scratch and confirm it works please? Else I will consider this done.

**Comment by MAD-OVERLORD** [comment]
@gambhiro + @mfeemster 
I might be wrong since i not have compiled from scratch nor that i had the time to look into the code for now, because i am still fighting with some severe problems with emberrender, that renders the whole GPU rendering abilities almost useless in terms of overall speed on over 1000 different still renders, compared to what i had achieved on a CPU with flam3-render, but that i will post separately, so the main problem i assume(didn't see any related code commits, which would change it) that probably still exists here is, that even if the flam3-palettes.xml(How do we underlay this gray in github?) gets copied to the right place, emberrender seems not to search at these places by default from what i could see in a strace
open("flam3-palettes.xml", O_RDONLY) = -1 ENOENT (No such file or directory)
, what would be the proper behavior for any normal software, so that the average dumb user doesn't have to know these places and the according parameter, before he can start to do anything with emberrender ;)

**Comment by MAD-OVERLORD** [comment]
I know, i was a rape victim of micro-soft myself till vista, were it started to hurt so much, that i just couldn't take anymore, so i know the worst of both worlds now =S

Sounds relatively good, thank you very much for cooperating with us aliens from planet GNU+Linux
My only suggestion would be to add /home/$usr/.fractorium or/and the newer less messy /home/$usr/.config/fractorium, if you ever would install some config.conf files, which are probably called Config.ini in your world, because that is the "user programfiles" place in our world ;)
