### ISSUE TITLE
toggle state to move the xforms or the preview

### ISSUE THREAD

**Issue by gambhiro** [mfeemster/fractorium#40]
One sometimes works on fractals where only a small part of it is going to be displayed, so there is a high scale factor and precise position applied to show only the featured bit.

I really liked that the xforms are displayed over the preview window, it saves a lot of screen space.

But in a case like these scaled fractals, the zoom out of view, so one can't manipulate them. I don't think it is necessary to scale and pan the xforms along with the preview, it would be better if they didn't move.

The best would be a button and key binding to toggle whether scaling / panning affects the xforms in the display (for fine maipulation), or scaling / panning the preview (for looking at details).

**Comment by mfeemster** [comment]
This is possibly something I can look at. Someone else mentioned this same thing (not sure if it was you). I will leave this open because it sounds like a good idea, but I likely won't be able to get to it until around March/April of next year.

**Comment by gambhiro** [comment]
I should try the locking feature in f10e4e610 . Does this stop the xforms from zooming away?

**Comment by mfeemster** [comment]
Yes, you are the third person to request this so far so I implemented it in that commit. It might not be fully perfect right now though. I have a lot of code in the works that I'll be committing soon.

If you see any problems with it, hold off on submitting bugs as they'll likely be fixed in the next commit.

Note you will see some jitter with the xforms when rapidly zooming. This is only cosmetic and is unfixable.

**Comment by mfeemster** [comment]
This work has been committed. Please see commit notes and verify it works as you expected. Close if it looks good.

**Comment by gambhiro** [comment]
Excellent, works like a charm!
