### ISSUE TITLE
Severe problems on rendering 1000s of different flames with emberrender on GPU

### ISSUE THREAD

**Issue by MAD-OVERLORD** [mfeemster/fractorium#55]
Before you get a headache from my observations down there, what i suggest to solve these problems is:
1) In my tests quality=500,estimator=3 was almost the maximum(in terms of speed gain over the CPU renderings) we could use with --opencl @720p, so we really need params like: --quality-override=\<val>   --estimator-override=\<val>   and maybe --passes-override=\<val> like you made with --supersample=\<val> to be able to handle big batches of flames which may have quality=2000 estimator=11 set, like electricsheeps usually do(Your --qs=\<val> would of course be sufficient if all flames had the same quality, but in case of my gallery and other stuff from the web, where we had qualities ranging from 5-4000 mixed all together, i think my suggestion would be superior)

Whilst emberanimate may reach an reasonable speed boost with --opencl on a particular well configured/optimized flame when rendering some series of it as an animation, emberrender on 1000s of different flames, with different non optimized configurations, had quiet a bit longer to render those 1000 flames and not to mention, before it even rendered them, it crapped out on many and some did render for over 7minutes on a flame, which i had rendered with flam3-render in a couple of seconds.
That was on my own flame gallery, which is more focused on simple eye appealing art, compared to the totally overblown alien abduction electricsheeps usually are, so there were not 100Xforms or to complicated stuff going on.
With electricsheeps, things are even worse, most of them i had tested, crapped out at rendering, here are some examples of these miraculous alien abductions which won't render at all without massively lowering their quality and estimator values as my point 1) suggestion would handle in batch mode:
[Flames-from-the-electricsheep-website.zip](https://github.com/mfeemster/fractorium/files/107143/Flames-from-the-electricsheep-website.zip)
Stage = filtering, progress = 100%, eta = 0.00sError: image rendering failed, skipping to next image.
MakeAndGetFinalAccumProgram
RunFinalAccum

And that was on a not so bad gaming machine:
OpenCL Info: 
Platform 0: NVIDIA Corporation NVIDIA CUDA OpenCL 1.2 CUDA 7.5.23
Device 0: NVIDIA Corporation GeForce GTX 870M
CL_DEVICE_OPENCL_C_VERSION: OpenCL C 1.2 
CL_DEVICE_LOCAL_MEM_SIZE: 49'152
CL_DEVICE_LOCAL_MEM_TYPE: 1
CL_DEVICE_MAX_COMPUTE_UNITS: 7
CL_DEVICE_MAX_READ_IMAGE_ARGS: 256
CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 16
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 805'257'216
CL_DEVICE_ADDRESS_BITS: 64
CL_DEVICE_GLOBAL_MEM_CACHE_TYPE: 2
CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 128
CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 114'688
CL_DEVICE_GLOBAL_MEM_SIZE: 3'221'028'864
CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65'536
CL_DEVICE_MAX_CONSTANT_ARGS: 9
CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
CL_DEVICE_MAX_WORK_GROUP_SIZE: 1'024
CL_DEVICE_MAX_WORK_ITEM_SIZES: 1'024, 1'024, 64

while true; do date; nvidia-smi -a | grep -i Used; sleep 1; done >> /tmp/Nvidia.log
showed me, that even if my whole desktop freezes terribly on rendering these electric sheep, that it is only a matter on the graphical side, the rest works fine and shows also, that never during the rendering till the "crash" and after, there was more GPU ram consumption then 400mb of the 3gb, so that is not the problem.

Probably i forgot the most things i have tested, but i believe it boils down to the things i suggested in point 1). and point 2).

**Comment by mfeemster** [comment]
Options: These are good ideas for rendering a large batch gotten from various sources. I will add the following to specify absolute values:
--quality
--demin
--demax
Note that I do not have the term "override" in them. This is to be consistent with the existing option --supersample, and also to make them shorter.

Performance: The images posted here: https://github.com/mfeemster/fractorium/files/107143/Flames-from-the-electricsheep-website.zip

work fine on my machine for both CPU and GPU in both single and double precision modes. I wrote a Powershell script like so:

$fileOne = "..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01241.flam3";

cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=33 --suffix=_f32_cpu
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=64 --suffix=_f64_cpu
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=33 --suffix=_f32_gpu --opencl
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=64 --suffix=_f64_gpu --opencl

$fileOne = "..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01573.flam3";

cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=33 --suffix=_f32_cpu
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=64 --suffix=_f64_cpu
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=33 --suffix=_f32_gpu --opencl
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=64 --suffix=_f64_gpu --opencl

$fileOne = "..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.03423.flam3";

cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=33 --suffix=_f32_cpu
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=64 --suffix=_f64_cpu
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=33 --suffix=_f32_gpu --opencl
cmd.exe /c EmberRender.exe --in=$fileOne --verbose --name_enable --bits=64 --suffix=_f64_gpu --opencl

And got the following results which look fine and perform exactly as I'd expect:

Using 4 automatically detected threads.

Iters ran/requested: 947,200,000 / 947,200,000 (100.00%)
Bad values: 0
Render time: 1m 4.69s
Pure iter time: 1m 2.77s
Iters/sec: 15,089,049

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01241_f32_cpu.png
Done.

Finished in: 1m 5.18s
Using 4 automatically detected threads.

Iters ran/requested: 947,200,000 / 947,200,000 (100.00%)
Bad values: 0
Render time: 1m 9.23s
Pure iter time: 1m 7.33s
Iters/sec: 14,069,067

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01241_f64_cpu.png
Done.

Finished in: 1m 9.73s
Using OpenCL to render.
Platform: Advanced Micro Devices, Inc. AMD Accelerated Parallel Processing OpenCL 2.0 AMD-APP (1912.5)
Device: Advanced Micro Devices, Inc. Tahiti

Iters ran/requested: 947,224,576 / 947,200,000 (100.00%)
Render time: 3.17s
Pure iter time: 0.49s
Iters/sec: 1,937,064,572

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01241_f32_gpu.png
Done.

Finished in: 3.92s
Using OpenCL to render.
Platform: Advanced Micro Devices, Inc. AMD Accelerated Parallel Processing OpenCL 2.0 AMD-APP (1912.5)
Device: Advanced Micro Devices, Inc. Tahiti

Iters ran/requested: 947,224,576 / 947,200,000 (100.00%)
Render time: 4.33s
Pure iter time: 0.98s
Iters/sec: 961,649,315

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01241_f64_gpu.png
Done.

Finished in: 5.09s
Using 4 automatically detected threads.

Iters ran/requested: 947,200,000 / 947,200,000 (100.00%)
Bad values: 0
Render time: 50.17s
Pure iter time: 49.03s
Iters/sec: 19,318,390

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01573_f32_cpu.png
Done.

Finished in: 50.71s
Using 4 automatically detected threads.

Iters ran/requested: 947,200,000 / 947,200,000 (100.00%)
Bad values: 0
Render time: 55.33s
Pure iter time: 54.13s
Iters/sec: 17,498,291

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01573_f64_cpu.png
Done.

Finished in: 55.89s
Using OpenCL to render.
Platform: Advanced Micro Devices, Inc. AMD Accelerated Parallel Processing OpenCL 2.0 AMD-APP (1912.5)
Device: Advanced Micro Devices, Inc. Tahiti

Iters ran/requested: 947,224,576 / 947,200,000 (100.00%)
Render time: 2.81s
Pure iter time: 0.53s
Iters/sec: 1,804,237,287

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01573_f32_gpu.png
Done.

Finished in: 3.63s
Using OpenCL to render.
Platform: Advanced Micro Devices, Inc. AMD Accelerated Parallel Processing OpenCL 2.0 AMD-APP (1912.5)
Device: Advanced Micro Devices, Inc. Tahiti

Iters ran/requested: 947,224,576 / 947,200,000 (100.00%)
Render time: 3.30s
Pure iter time: 0.67s
Iters/sec: 1,424,397,858

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.01573_f64_gpu.png
Done.

Finished in: 4.12s
Using 4 automatically detected threads.

Iters ran/requested: 947,200,000 / 947,200,000 (100.00%)
Bad values: 0
Render time: 49.91s
Pure iter time: 48.09s
Iters/sec: 19,697,631

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.03423_f32_cpu.png
Done.

Finished in: 50.47s
Using 4 automatically detected threads.

Iters ran/requested: 947,200,000 / 947,200,000 (100.00%)
Bad values: 0
Render time: 53.40s
Pure iter time: 51.42s
Iters/sec: 18,420,847

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.03423_f64_cpu.png
Done.

Finished in: 53.97s
Using OpenCL to render.
Platform: Advanced Micro Devices, Inc. AMD Accelerated Parallel Processing OpenCL 2.0 AMD-APP (1912.5)
Device: Advanced Micro Devices, Inc. Tahiti

Iters ran/requested: 947,224,576 / 947,200,000 (100.00%)
Render time: 3.10s
Pure iter time: 0.57s
Iters/sec: 1,661,797,501

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.03423_f32_gpu.png
Done.

Finished in: 4.24s
Using OpenCL to render.
Platform: Advanced Micro Devices, Inc. AMD Accelerated Parallel Processing OpenCL 2.0 AMD-APP (1912.5)
Device: Advanced Micro Devices, Inc. Tahiti

Iters ran/requested: 947,224,576 / 947,200,000 (100.00%)
Render time: 3.45s
Pure iter time: 0.84s
Iters/sec: 1,128,992,343

Writing ..\..\..\Data\MAD-OVERLORD\Flames-from-the-electricsheep-website\electricsheep.245.03423_f64_gpu.png
Done.

Finished in: 4.30s

The failure you saw is one that myself and many others have seen. It's an ongoing issue that I haven't figured out how to resolve. It has to do with Nvidia cards crashing while doing the second phase of the algorithm, density filtering. It stresses the card extremely hard. Try running these again with the new option --demax at some value like 8 or 9 and see if that works. If not, keep decrementing it by 1 until it completes. This is the value you'll need to use on your card. TBH, it shouldn't make much difference in the quality of the output images if you're doing a lot of iters.

I apologize for not having this information posted anywhere else, but with so much code to write, I have little time for documentation. I will get to it later in the year.

Certain variations are hard on the GPU, I will catalog them at some point. For right now, I know that Nvidia almost completely chokes on synth:

http://mfeemster.deviantart.com/journal/Fractorium-Beta-0-9-9-3-Released-585079013

The UI freezes sound bad, but are not entirely unexpected. I definitely get a system-wide UI slowdown/freeze when doing heavy rendering on the GPU. There is no way around it because this algorithm stresses the card very hard. However, that slowdown might be worse on Linux because as a general rule, drivers are worse there. There is nothing I can do about this, although I will note it in future documentation.

**Comment by MAD-OVERLORD** [comment]
@mfeemster 
Amazing how vivid you keep this project, even on weekends you don't take a rest, i hope you don't overdue yourself with that very nice project, i mean we users of fractal software are usually just a bunch of stoned hippies and artists which are anyway lost in time and drugs/fractals, so you really don't have to be that much ahead of all happenings like you probably must be in your job, where there seems to be a real need to be that much ahead of the donkey-fuckers newest magic carpet stealth technology :D (As always, don't get me wrong please, i'm just addicted to talk the utter most cryptic bullshit that even tops "truth", but i never mean it in a attacking fashion, basically i really just wanted to say, be somewhat careful of the addicting and life slurping powers which open source projects sadly have these days, thanks to platforms like github and the inherent illusion, that software is something like a product, that should be perfect and finished one day, so if you ever realize that you just can't stop running towards the burnout trap anymore, remember that you can always puke over the crocodiles and snakes to completely escape the heavy load on your "shoulders" for a while ;) )

Today i sadly can't keep up with all the searches, compiling and tests i should do, and next week i have too much to do, so i hope you will not be too terrified if these things rest in a open state for some days, else you can close them, since i'm more than fully confident in your abilities of fixing the "issues", but i will surly provide you with the results from planet GNU+Linux as fast as i can.

I wish you a nice weekend.

**Comment by MAD-OVERLORD** [comment]
Since the --quality and --demax Fix worked right and the essence of the problem continues at
https://github.com/mfeemster/fractorium/issues/64
i close this now.
Thank you very much for the new params :)
