### ISSUE TITLE
[Linux] xml files in home directory cause floating point exception

### ISSUE THREAD

**Issue by nonno-cicala** [mfeemster/fractorium#72]
On Gentoo if I have an XML file with extension .xml in my home directory and I try to run fractorium it says it could not load palette file and crashes with a floating point exception.

This code is enough to cause the crash:
`<?xml version="1.0" encoding="UTF-8"?>
<tag>
</tag>`

Thank you again for this awesome program!

**Comment by mfeemster** [comment]
Hi nonno, thanks for the kind words and glad you are liking it. Sorry to hear you are crashing though. I will admit I didn't add very much robust error checking with palette parsing just because I always expected only flam3-palettes.xml to be present. Now that we are supporting multiple paths and palette files, I will make the code more error tolerant. Give me a day or two on this one.

**Comment by mfeemster** [comment]
Fix is committed. I assume you are building from source? If so, can you please confirm the fix worked?

**Comment by nonno-cicala** [comment]
It worked! Thanks! :)
