### ISSUE TITLE
Crackle variation severely increasing render time

### ISSUE THREAD

**Issue by MightyLight** [mfeemster/fractorium#78]
Tested against a big bunch of variations, render speed with other variation on the transform was ~ 1.5 sec (230 quality), crackle increases it to 7 seconds. As far as I tested, it only happens with crackle.

**Comment by mfeemster** [comment]
This is not a bug. Different variations do different things and will therefore have different impacts on performance. You can verify this by trying crackle with JWildfire and Apophysis and see how much it adds to their render times too.

I will note that while almost all variations have an identical implementation on the CPU and GPU, crackle differs on the GPU. Normally, on the CPU it stores a cached set of points that it looks up for most cases, and only recalculates new points on occasion (track down the original crackle code to see what I mean). I tried this on the GPU and it worked fine for AMD, but crashed Nvidia hard. I figured this was due to extreme warp divergence between threads that took the cached point path and threads that took the path to compute the new point. I had to scrap it and just always compute a new point which makes it slower.

That's unreleased documentation you'll only get here =)

**Comment by MightyLight** [comment]
Oh, should've tested in CPU mode to note this difference. Will take note of this.
Thanks Matt.

**Comment by mfeemster** [comment]
You'll be happy to know that the long paragraph above no longer applies. I traced down the source of the crash to something else. With my latest commit, it works fine using the same caching mechanism on the GPU as the CPU uses. I verified with AMD and Nvidia with SP and DP. The speed increase is 5-10x. You can either build it from source now or wait till the next release.

**Comment by MightyLight** [comment]
Good too know Matt!


2016-04-15 0:13 GMT-03:00 Matt Feemster <notifications@github.com>:
