### ISSUE TITLE
emberrender vs jwildfire

### ISSUE THREAD

**Issue by boosth** [mfeemster/fractorium#84]
I have some flames generated with jwildfire that I would like to render with emberrender to leverage the OpenCL support.

I have found that the flames are not rendered the same as they are with jwildfire.

In jwildfire the flock is animated to transform over 320 frames per flame but in emberrender I see varying results. I have three different flames. The first flame renders an animatiion sequence but the visuals are almost completely different from the render done with jwildfire. The second and third flames render the image correctly but they don't follow the animation sequence so I end up with a sequence of the same image repeated for 320 frames.

Do you have any suggestions?

**Comment by mfeemster** [comment]
I am not too familiar with jwf, so my help may be of limited use here, but I'll see what I can do.

Make sure you have the latest version, 0.9.9.5

Can you post the original flames you used to make the sequence? If you don't want to share them publicly, can you email them to me?

Also post the command line you used to make the sequence. If you generated it with JWildfire, skip this step.

Post the actual animation sequence file. Email me if you don't want to share.

We have two issues here, the flames looking different, and them being animated differently.

For the first, are you sure that every variation you use in jwf is also supported in Fractorium?

Also, the command line uses single precision by default. Can you try running with --bits=64 and see if you still get different looking images? Most will look the same with SP/DP but some will look different.

Hopefully we can get this resolved.

**Comment by boosth** [comment]
I am running the latest git on Linux 64bit. I used jwf to create the animation sequence. I am not an expert so I am just trying to work with the output of jwf because that is what I have to work with for now. I'm not sure about the limitations differences between the two so it might just be that the variations I have are not supported in fractorium. I didn't do much to generate the sequences.

Here's a link to the flock I generated with jwf:  http://iguanapro.com/f3.tar.bz2

I'm using this commandline for emberrender:  emberrender --in=flameseq10960.flame --ss=1.986 --quality=1000 --format=png --verbose --progress --opencl

The output of the first 320 flames in the sequence with emberrender is significantly different from the output of jwf's renderer.

You can view a video of the flames rendered by jwf. The first 2 flames are rendered in jwf and the last flame is rendered in emberrender. This is where I noticed that emberrender was behaving unexpectedly.

http://iguanapro.com/out.mp4

Here's a folder with the first flame rendered in emberrender which I did as a test after spotting the inconsistency in the video above:

http://iguanapro.com/f3-image.tar.bz2

I'm not sure why these ones come out so small in comparison to the other flames. The commandline used to render them is the same for all three. The second and third flame are rendered at 1920x1080 as expected. This first flame is mostly rendered at 158x119 but it jumps around a bit towards the end of the sequence.

I'm using a NVIDIA geforce GTX 850M with nvidia opencl drivers. 

Here's an example of the output from emberrender :

- first flame

Finished in: 0.14s
Using OpenCL to render.
Platform: NVIDIA Corporation NVIDIA CUDA OpenCL 1.2 CUDA 7.5.23
Device: NVIDIA Corporation GeForce GTX 850M
Stage = iterating, progress = 100%, eta = 0.00s                                                   
Stage = filtering, progress = 100%, eta = 0.00s                                                 
Iters ran/requested: 18,808,832 / 18,802,000 (100.04%)
Render time: 0.03s
Pure iter time: 0.02s
Iters/sec: 854,946,909

Writing flameseq10094.png
Done.


- second flame

Finished in: 0.14s
Using OpenCL to render.
Platform: NVIDIA Corporation NVIDIA CUDA OpenCL 1.2 CUDA 7.5.23
Device: NVIDIA Corporation GeForce GTX 850M
Stage = iterating, progress = 100%, eta = 0.00s                                                   
Stage = filtering, progress = 100%, eta = 0.00s                                                 
Iters ran/requested: 18,808,832 / 18,802,000 (100.04%)
Render time: 0.03s
Pure iter time: 0.02s
Iters/sec: 854,946,909

Writing flameseq10137.png
Done.

**Comment by mfeemster** [comment]
The first problem is that you're using the wrong program. emberanimate is what you want to use for animations.

The rest of the problems I will look at later and get back to you in about 5 or 6 hours.

**Comment by mfeemster** [comment]
Ok, I took a look.

1) Jwf uses a lot of advanced features that only it supports. Your flames are loaded with these and therefore will not look the same anywhere else. It would be nice if there was some type of "flame standard", but there isn't and likely never will be. Each program has taken off on its own path from the original flam3 Xml format. Andreas has done some truly amazing things with Jwf that Fractorium won't ever do. So there will always be mostly incompatible.

2) You also use variations which Fractorium does not support.

3) The reason for the changes in size are because their size changes:
size="80 60"
size="1920 1080"
size="967 544"

If you use emberanimate, it will force all of their sizes to be the same and print a warning message.

4) If you want to do some animation, you need three steps:

-Make your still images, these are your keyframes. Put them into a single Xml file. This can be done by either adding new flames in Fractorium and saving the entire file as Xml. Or by dragging existing flames into an already open file while holding the Ctrl key. Sadly, you can't change the order of them in Fractorium, so you'd need to do that manually in the Xml file.

-Create a sequence using embergenome. The syntax is the same as the original flam3-genome.

-Use the Xml output of that step and feed it into emberanimate.

The documentation from flam3 is better for that animation than mine is:

https://github.com/scottdraves/flam3/wiki

I apologize for not having this detailed, but working on the code hasn't left much time for documentation. I am currently working on a website, so that should help when it's ready in 3 or 4 months.

5) I know this sounds cumbersome. I always wanted Fractorium to have an animation editor to free the user from tedious command line programs. Jwf and Chaotica have implemented this, but I was just never able to do it. I will note however, that once you have your sequence, you can render it as an animation in the final render dialog of Fractorium.

**Comment by boosth** [comment]
Thanks for looking into this Matt. The information you provided here is very useful. IIUC your goal for Fractorium is to enable realtime animation with GPUs. That's very cool and powerful.

**Comment by mfeemster** [comment]
You're welcome. Sadly, the realtime animation thing never came about. I don't think I'll ever do it in this lifetime. However, if someone were to do it, it would be a very stripped down version of what's supported for still images. Only certain variations, a max number of xforms, no DE, no supersampling, etc... It would also require a new threading model for OpenCL code compilation. On and on.

**Comment by mfeemster** [comment]
One final comment, is there a reason you are building from source and not using the installers? Just curious, I like to get an idea of how/why/where people are using this program. Thanks.

**Comment by boosth** [comment]
I compiled from source because I like to use the latest code from development code where possible and I will have a read through the code base to get a better understanding of the application. However if the app was already included in the debian repos I probably would have tried that first with apt-get.

IfI can make any contributions I will feed them back to you.
