### ISSUE TITLE
Changing "quality" attribute in xml does nothing

### ISSUE THREAD

**Issue by Atm55** [mfeemster/fractorium#88]
I have a .flame file with around 60 or so fractals. Some only look good at 5000 quality, others are peachy fine at just 300. It makes sense to only use as much quality as a fractal needs to lower the time of render.

I tried to manually change the "quality" attribute in the xml file for each individual <flame> tag, but the renderer still uses the same quality setting for all fractals. Changing other attributes in the .flame file, like "zoom" or "brightness", works fine; only renderer settings ("quality", "supersample", etc.) don't work.

Also, thanks for this amazing program! :-)

**Comment by mfeemster** [comment]
Hi Atm,

This is intentional. Quality and supersample are ignored when loading into the editor because these can greatly affect rendering time. They are also ignored because the main editor is only meant to be a preview window, so it doesn't make much sense to do editing at high qualities. That way, if you drag in something with 10000 quality specified in the Xml, the program doesn't grind to a crawl. The same is true for supersample because it also affects performance quite a bit.

So the suggested workflow is to get it looking right in the main window, then use the final render dialog to render it exactly how you want.

You are correct that even there, the quality value is set for all flames being rendered. I guess I hadn't though about doing different values for different flames. I always figured the user would pick one sufficiently large value then render all with it.

However, if you absolutely must render the qualities and supersamples as-is, then you are in luck: the command line tools will do this for you. Go to the installation folder which is under Program Data in Windows and do this:

`emberrender --in=C:\path\to\your\test.flame`

To render on the GPU using device 0:

`emberrender --in=C:\path\to\your\test.flame --opencl`

To render on the GPU using a different device:

`emberrender --in=C:\path\to\your\test.flame --opencl --device=1`

To render on the GPU using a multiple devices, separate them with commas:

`emberrender --in=C:\path\to\your\test.flame --opencl --device=0,1,2`

Query the OpenCL capable devices on your machine with:

`emberrender --opencl`

Get help with:

`emberrender --help`

Other options are --verbose and --progress to get more information as the render proceeds.

Let me know if this is sufficient to solve your problem.

**Comment by Atm55** [comment]
Yup, custom quality likely isn't the most important feature. I only need it since I render a load of fractals daily.

Either way, your suggestion works like a charm, thanks! Render time is down from 1 minute to 4 seconds in some cases, without a noticeable drop in quality!

**Comment by mfeemster** [comment]
Glad it worked. FYI, I am currently working on a website that will document these types of things.

Closing this issue.
